# Generated by Django 4.2.13 on 2024-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientUser', '0005_clientuser_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('titel', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('last_date', models.DateField()),
                ('applicant', models.ManyToManyField(blank=True, related_name='applicants', to='clientUser.clientuser')),
            ],
        ),
    ]
