# Generated by Django 4.2.13 on 2024-07-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClintUser',
            new_name='ClientUser',
        ),
    ]
