# Generated by Django 4.2.13 on 2024-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientUser', '0002_rename_clintuser_clientuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
