# Generated by Django 4.2.13 on 2024-08-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientUser', '0003_alter_clientuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
