# Generated by Django 4.2.13 on 2024-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientUser', '0004_clientuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
